### ISSUE TITLE
Eliminate non-inclusive language

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/ha_cluster#93]
Hello, we have a project to eliminate non-inclusive language from the linux-system-roles.

Running a utility `woke` (now it's supported in `tox`. please install the latest `tox-lsr` and run `tox -e woke`), two non-inclusive words are reported - `dummy` and `slave`.

Can we replace them with more appropriate words? For the word `dummy`, `placeholder`, and `sample` are recommended. For `slave`, `secondary`, `replica`, `responder`, `device,worker,proxy`, and `performer` are the candidates. It looks to me that replacing `dummy` is straightforward. But not certain about `slave`. I wonder if it is doable? Or if we replace it, does it break the ha cluster? Thanks!

**Comment by tomjelinek** [comment]
The HA Cluster team have been working on replacing non-inclusive language for several years. Major changes and progress have been done in RHEL 8.0 release, then with 9.0 / 8.5. However, due to the need of backward compatibility, we cannot just simply stop using old terms and keywords.

For the progress done, see for example:
* https://bugzilla.redhat.com/show_bug.cgi?id=1542288
* https://bugzilla.redhat.com/show_bug.cgi?id=1885293
* https://wiki.clusterlabs.org/wiki/Pacemaker_2.0_Configuration_Changes
* https://wiki.clusterlabs.org/wiki/Pacemaker_2.1_Changes

When writing the role, I took care to avoid using non-inclusive language as much as possible. I can remove non-inclusive language from the role completely. That would, however, make the role incapable of configuring HA Cluster on older RHEL releases.

For the backward compatibility reasons, `master` and `slave` cannot be removed. For example here the role checks if it can use the new term or needs to stick to the old one: https://github.com/linux-system-roles/ha_cluster/blob/2bf1767a9cf2e4d58aa9b0d7625c742402b298f3/tasks/create-and-push-cib.yml#L187-L195 

It is a similar story with `dummy`. I can rename cluster resources in tests and `README.md` form `dummy` to `sample`. However, `ocf:pacemaker:Dummy` must be kept in place until it is renamed in pacemaker. And even after that, the role would have to keep `ocf:pacemaker:Dummy` in tests for backward compatibility.

**Comment by nhosoi** [comment]
Thank you, @tomjelinek. I've opened a pr https://github.com/linux-system-roles/ha_cluster/pull/97 to introduce the conscious language check action `woke.yml` and to clean up / workaround the problematic words. To be honest, the latter part is quite invasive. I'd appreciate if you could review the pr. Thanks!

**Comment by tomjelinek** [comment]
Resolved by #97
